### ISSUE TITLE
View transactions by budget period

### ISSUE THREAD

**Issue by BenjaminGroseclose** [BudgetSquirrel/ApplicationWebApi#7]
As a user I want to be able to see all the transactions in a budget period. 

I should be able to filter this by budget as well.

**Comment by BenjaminGroseclose** [comment]
So I think this should be by date instead of budget period. We could do it by budget period but I think the user would better experience for them to enter two dates, instead of certain budget periods. 

And have them pass in what budget they are wanting transactions from.

**Comment by ianbro** [comment]
> So I think this should be by date instead of budget period. We could do it by budget period but I think the user would better experience for them to enter two dates, instead of certain budget periods.
> 
> And have them pass in what budget they are wanting transactions from.

I was picturing both. The main page would show a breakdown of how they're doing in all of their budgets for the current budget period. They could click on a budget and it would show them details like all the transactions logged in the current budget period.
But then, they could go to a reporting page where they could filter transactions by budget plus [budget period or date]. Most of the time, the user just wants to know how they're doing this month (budget period). But from time to time they may want to look back by date.
